package Modelo;
// Generated 3/12/2020 04:58:59 PM by Hibernate Tools 4.3.1



/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private Integer id;
     private Libro libro;
     private Usuario usuario;

    public Prestamo() {
    }

    public Prestamo(Libro libro, Usuario usuario) {
       this.libro = libro;
       this.usuario = usuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


