package Modelo;
// Generated 3/12/2020 04:58:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String cedula;
     private String nombre;
     private Date fechaNac;
     private String sexo;
     private boolean activo;
     private String tipo;
     private Set prestamos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String cedula, String nombre, Date fechaNac, String sexo, boolean activo, String tipo) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.fechaNac = fechaNac;
        this.sexo = sexo;
        this.activo = activo;
        this.tipo = tipo;
    }
    public Usuario(String cedula, String nombre, Date fechaNac, String sexo, boolean activo, String tipo, Set prestamos) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.fechaNac = fechaNac;
       this.sexo = sexo;
       this.activo = activo;
       this.tipo = tipo;
       this.prestamos = prestamos;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }




}


